### ISSUE TITLE
Index.html example mesh does not load on Chrome/OperaNext (Probably all Webkit based browsers)

### ISSUE THREAD

**Issue by thorsummoner** [jeromeetienne/threejsboilerplate#9]
Env Windows 8.1 x64

Chrome `Version 34.0.1847.131 m` Failed: 
![image](https://cloud.githubusercontent.com/assets/1320336/2812610/017f2e42-ce65-11e3-81b8-7bcb9d098b56.png)

Opera `Version: 20.0.1387.91` Failed: 
![image](https://cloud.githubusercontent.com/assets/1320336/2812613/35312cd6-ce65-11e3-9eac-08265071fb25.png)

Firefox worked as expected

Internet Explorer worked as expected (9 or later)

**Comment by confile** [comment]
same here

**Comment by jeromeetienne** [comment]
http://jeromeetienne.github.io/threejsboilerplate/ please try this url which has been updated

**Comment by thorsummoner** [comment]
@jeromeetienne The given link appears to do something really haneous on Firefox, like the rendering engine won't even paint the browsers own tab properly!

**Comment by jeromeetienne** [comment]
@thorsummoner i think it is a problem on your system. because the above link works well on numerous systems. here is the list
- on chrome/safari/firefox on macosx
- on chrome chromeos
- on safari/chrome IOS8
- on chrome/firefox on android

**Comment by thorsummoner** [comment]
@jeromeetienne You must be right, confirmed page loads on

Win 8.1 - Chrome Version 37.0.2062.124 m, and
Win 8.1 - Firefox 32.0.3
